#!/bin/sh

# resolve base url
_adoptor() {
  url=$(git config --get remote.origin.url)
  domain=$(echo "$url" | sed "s/git@//" | sed "s/:.*//")
  user=$(echo "$url" | sed "s/git@.*://" | sed "s/\/.*//")
  repo=$(echo "$url" | sed "s/git@.*\///" | sed "s/\.git//")
  branch=$(git symbolic-ref --short HEAD)
  export url domain user repo branch
}

# to top page
_go_top() {
  open "https://$domain/$user/$repo"
}

# to branch page
_go_branch() {
  case $1 in
  "") open "https://$domain/$user/$repo/branches" ;;
  ".") case $domain in
    github.com) open "https://$domain/$user/$repo/tree/$branch" ;;
    bitbucket.org) open "https://$domain/$user/$repo/branch/$branch" ;;
    esac ;;
  *) case $domain in
    github.com) open "https://$domain/$user/$repo/tree/$1" ;;
    bitbucket.org) open "https://$domain/$user/$repo/branch/$1" ;;
    esac ;;
  esac
}

# to commit page
_go_commit() {
  open "https://$domain/$user/$repo/commits"
}

# usage
_repoj_usage() {
  echo "Usage: repoj [OPTION] [ARGUMENT]
Open the repository in your default browser.

Without ARGUMENT, open the top page of the repository.
  b   Open the branch page (Without argument, a branch listing page)
  c   Open the commit listing page
  h   Display this help and exit" >&2
}

repoj() {
  if [ $# -eq 0 ]; then
    _adoptor && _go_top
  else
    case $1 in
    b) _adoptor && _go_branch "$2" ;;
    c) _adoptor && _go_commit "$2" ;;
    *) _repoj_usage && exit 2 ;;
    esac
  fi

}

repoj "$@"
